# Generated by Django 3.2.9 on 2022-03-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_st', models.CharField(default='Student', max_length=13)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.BigIntegerField(default=0)),
                ('disability', models.CharField(default='', max_length=40)),
                ('classes', models.CharField(default='', max_length=40)),
                ('course', models.CharField(default='', max_length=40)),
                ('lang', models.CharField(default='', max_length=40)),
                ('pref_lang', models.CharField(default='', max_length=40)),
                ('school', models.CharField(default='', max_length=40)),
                ('paid_unpaid', models.CharField(default='', max_length=40)),
                ('location', models.CharField(default='', max_length=40)),
                ('pincode', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_st', models.CharField(default='Scribe', max_length=13)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.BigIntegerField(default=0)),
                ('qualification', models.CharField(default='', max_length=40)),
                ('qual_course', models.CharField(default='', max_length=40)),
                ('location', models.CharField(default='', max_length=40)),
                ('pincode', models.BigIntegerField(default=0)),
                ('lang1', models.CharField(default='', max_length=40)),
                ('lang2', models.CharField(default='', max_length=40)),
                ('lang3', models.CharField(default='', max_length=40)),
                ('classes', models.CharField(default='', max_length=40)),
                ('course', models.CharField(default='', max_length=40)),
                ('paid_unpaid', models.CharField(default='', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
